version: '3'

services:
  rest-api:
    image: haritech101/medical-platform-rest-api
    ports:
      - "37082:8080"
    environment:
      - MONGO_HOST=db
      - MONGO_DB=medicalPlatform
    depends_on:
      - db
  db:
    image: mongo:5.0.22
    volumes:
      - "/additional/db/medical-platform:/data/db"

